name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: composer-php
  # You may pin to the exact commit or the version.
  # uses: nick-zh/composer@7d8fabe9f01d0d721a55e712b5fa83d35d584df1
      uses: nick-zh/composer@php7.4
 
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
